version: "3"

services:
  fabric:
    image: itzg/minecraft-server:latest
    ports:
      - 25565:25565
    volumes:
      - "/root/MC/fabric:/data"
      - "/root/fabric/world:/world"
    environment:
      EULA: "TRUE"
      VERSION: "1.18.1"
      TYPE: "FABRIC"
      MODS: "/mods"
      WORLD: "/world"
      DIFFICULTY: "hard"
      MAX_PLAYERS: "5"
      FORCE_GAMEMODE: "true"
      HARDCORE: "false"
      MODE: "survival"
      PVP: "true"
      ONLINE_MODE: "false"
      ALLOW_FLIGHT: "true"
      SERVER_NAME: "DD's Server"
      MOTD: "DD's Server"
      MEMORY: "6G"
      WHITELIST: ""
      OPS: "X_w_X"
      BROADCAST_CONSOLE_TO_OPS: "false"
      BROADCAST_RCON_TO_OPS: "false"
    restart: always